all:
	gcc double-free-and-write.c -o double-free-and-write
	gcc double-free-and-write.c -o double-free-and-write32 -m32
	gcc hello-world.c -o hello-world
	gcc hello-world.c -o hello-world32 -m32
	gcc invalid-free.c -o invalid-free
	gcc invalid-free.c -o invalid-free32 -m32
	gcc zero-allocation.c -o zero-allocation
	gcc zero-allocation.c -o zero-allocation32 -m32
	gcc negative-allocation.c -o negative-allocation
	gcc negative-allocation.c -o negative-allocation32 -m32
